### PR TITLE
[Tests] Years only have 12 months, and these tests started failing in December

### LINKED ISSUE #876: An in-range update of @storybook/addon-actions is breaking the build 🚨
## Version **3.2.17** of [@storybook/addon-actions](https://github.com/storybooks/storybook) was just published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/airbnb/react-dates/compare/greenkeeper%2F%40storybook%2Faddon-actions-3.2.17">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      @storybook/addon-actions
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      3.2.16
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      devDependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@storybook/addon-actions is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/airbnb/react-dates/builds/310978989?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v3.2.17</strong>

<p>2017-December-03</p>
<h4>Features</h4>
<ul>
<li>Add dotenv support for storybook in vue and react <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2345">#2345</a></li>
<li>Add addon jest <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2295">#2295</a></li>
<li>Addon-knobs: add number config options <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2371">#2371</a></li>
<li>Addon-info: Expose style for customization <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2370">#2370</a></li>
</ul>
<h4>Bug Fixes</h4>
<ul>
<li>Fix addon-actions in legacy Android browser <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2365">#2365</a></li>
<li>Remove superfluous vertical scrollbar in fullscreen <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2394">#2394</a></li>
<li>Made jest test file extension name optional <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2373">#2373</a></li>
<li>Render navigation and addons panels even when they are hidden <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2336">#2336</a></li>
<li>Fix wrong "withTests" examples + add documentation <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2398">#2398</a></li>
</ul>
<h4>Maintenance</h4>
<ul>
<li>Issue <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/2196" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="270070092" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/2196">#2196</a> - Set console.warn and console.error to throw in tests <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2297">#2297</a></li>
<li>Optimize CI workflow <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2331">#2331</a></li>
<li>Ignore shelljs in bithound <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2322">#2322</a></li>
<li>Fix netlify vue instance <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2386">#2386</a></li>
<li>Keep examples' deps up to date <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2353">#2353</a></li>
<li>Separate netlify instances <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2340">#2340</a></li>
<li>Issue 2196 fix unittest warnings <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2343">#2343</a></li>
</ul>
<h4>Documentation</h4>
<ul>
<li>Document return type of <code>date</code> knob (see <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/1489" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="244040321" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/1489">#1489</a>) <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2332">#2332</a></li>
</ul>
<h4>Dependency Upgrades</h4>
<details>
<summary>
72 PRs
</summary>
<ul>
<li>Update gatsby in /docs from 1.9.127 to 1.9.128 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2420">#2420</a></li>
<li>Update marked in /docs from 0.3.6 to 0.3.7 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2416">#2416</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.126" to "1.9.127" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.22" to "1.7.23" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.125" to "1.9.126" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.29" to "1.6.30" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.119" to "1.9.125" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.28" to "1.6.29" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-plugin-sharp</code> in <code>docs</code> from "1.6.21" to "1.6.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-autolink-headers</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-copy-linked-files</code> in <code>docs</code> from "1.5.21" to "1.5.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-images</code> in <code>docs</code> from "1.5.32" to "1.5.33" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-smartypants</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-source-filesystem</code> in <code>docs</code> from "1.5.8" to "1.5.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.21" to "1.7.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react-native</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/vue</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>danger</code> in <code>/</code> from "2.0.1" to "2.0.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint</code> in <code>/</code> from "4.11.0" to "4.12.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.8.0" to "2.9.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.3" to "3.1.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react-native</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>react-native</code> in <code>app/react-native</code> from "0.50.3" to "0.50.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/react</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/vue</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/vue</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>commander</code> in <code>/</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>lib/cli</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.2" to "3.1.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react-native</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/vue</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Update gatsby in docs from 1.9.118 to 1.9.119 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2354">#2354</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>ws</code> in <code>app/react-native</code> from "3.3.1" to "3.3.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.7.0" to "2.8.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>eslint-plugin-react</code> in <code>/</code> from "7.4.0" to "7.5.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Update gatsby in docs from 1.9.117 to 1.9.118 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2341">#2341</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.114" to "1.9.117" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Upgraded <code>gh-pages</code> in <code>docs</code> from "1.0.0" to "1.1.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Update gh-pages in / from 1.0.0 to 1.1.0 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2339">#2339</a></li>
<li>Upgraded <code>@types/react</code> in <code>addons/knobs</code> from "16.0.23" to "16.0.25" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>app/vue</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>examples/vue-kitchen-sink</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Update gatsby in docs from 1.9.112 to 1.9.114 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2333">#2333</a></li>
<li>Upgraded <code>@storybook/addon-actions</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addon-links</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addons</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/react</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Update @types/node in addons/knobs from 8.0.52 to 8.0.53 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2326">#2326</a></li>
</ul>
</details>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #877: An in-range update of @storybook/addon-info is breaking the build 🚨
## Version **3.2.17** of [@storybook/addon-info](https://github.com/storybooks/storybook) was just published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/airbnb/react-dates/compare/greenkeeper%2F%40storybook%2Faddon-info-3.2.17">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      @storybook/addon-info
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      3.2.16
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      devDependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@storybook/addon-info is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/airbnb/react-dates/builds/310979741?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v3.2.17</strong>

<p>2017-December-03</p>
<h4>Features</h4>
<ul>
<li>Add dotenv support for storybook in vue and react <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2345">#2345</a></li>
<li>Add addon jest <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2295">#2295</a></li>
<li>Addon-knobs: add number config options <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2371">#2371</a></li>
<li>Addon-info: Expose style for customization <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2370">#2370</a></li>
</ul>
<h4>Bug Fixes</h4>
<ul>
<li>Fix addon-actions in legacy Android browser <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2365">#2365</a></li>
<li>Remove superfluous vertical scrollbar in fullscreen <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2394">#2394</a></li>
<li>Made jest test file extension name optional <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2373">#2373</a></li>
<li>Render navigation and addons panels even when they are hidden <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2336">#2336</a></li>
<li>Fix wrong "withTests" examples + add documentation <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2398">#2398</a></li>
</ul>
<h4>Maintenance</h4>
<ul>
<li>Issue <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/2196" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="270070092" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/2196">#2196</a> - Set console.warn and console.error to throw in tests <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2297">#2297</a></li>
<li>Optimize CI workflow <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2331">#2331</a></li>
<li>Ignore shelljs in bithound <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2322">#2322</a></li>
<li>Fix netlify vue instance <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2386">#2386</a></li>
<li>Keep examples' deps up to date <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2353">#2353</a></li>
<li>Separate netlify instances <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2340">#2340</a></li>
<li>Issue 2196 fix unittest warnings <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2343">#2343</a></li>
</ul>
<h4>Documentation</h4>
<ul>
<li>Document return type of <code>date</code> knob (see <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/1489" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="244040321" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/1489">#1489</a>) <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2332">#2332</a></li>
</ul>
<h4>Dependency Upgrades</h4>
<details>
<summary>
72 PRs
</summary>
<ul>
<li>Update gatsby in /docs from 1.9.127 to 1.9.128 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2420">#2420</a></li>
<li>Update marked in /docs from 0.3.6 to 0.3.7 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2416">#2416</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.126" to "1.9.127" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.22" to "1.7.23" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.125" to "1.9.126" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.29" to "1.6.30" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.119" to "1.9.125" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.28" to "1.6.29" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-plugin-sharp</code> in <code>docs</code> from "1.6.21" to "1.6.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-autolink-headers</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-copy-linked-files</code> in <code>docs</code> from "1.5.21" to "1.5.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-images</code> in <code>docs</code> from "1.5.32" to "1.5.33" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-smartypants</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-source-filesystem</code> in <code>docs</code> from "1.5.8" to "1.5.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.21" to "1.7.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react-native</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/vue</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>danger</code> in <code>/</code> from "2.0.1" to "2.0.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint</code> in <code>/</code> from "4.11.0" to "4.12.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.8.0" to "2.9.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.3" to "3.1.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react-native</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>react-native</code> in <code>app/react-native</code> from "0.50.3" to "0.50.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/react</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/vue</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/vue</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>commander</code> in <code>/</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>lib/cli</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.2" to "3.1.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react-native</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/vue</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Update gatsby in docs from 1.9.118 to 1.9.119 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2354">#2354</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>ws</code> in <code>app/react-native</code> from "3.3.1" to "3.3.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.7.0" to "2.8.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>eslint-plugin-react</code> in <code>/</code> from "7.4.0" to "7.5.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Update gatsby in docs from 1.9.117 to 1.9.118 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2341">#2341</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.114" to "1.9.117" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Upgraded <code>gh-pages</code> in <code>docs</code> from "1.0.0" to "1.1.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Update gh-pages in / from 1.0.0 to 1.1.0 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2339">#2339</a></li>
<li>Upgraded <code>@types/react</code> in <code>addons/knobs</code> from "16.0.23" to "16.0.25" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>app/vue</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>examples/vue-kitchen-sink</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Update gatsby in docs from 1.9.112 to 1.9.114 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2333">#2333</a></li>
<li>Upgraded <code>@storybook/addon-actions</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addon-links</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addons</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/react</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Update @types/node in addons/knobs from 8.0.52 to 8.0.53 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2326">#2326</a></li>
</ul>
</details>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #878: An in-range update of @storybook/addon-options is breaking the build 🚨
## Version **3.2.17** of [@storybook/addon-options](https://github.com/storybooks/storybook) was just published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/airbnb/react-dates/compare/greenkeeper%2F%40storybook%2Faddon-options-3.2.17">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      @storybook/addon-options
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      3.2.16
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      devDependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@storybook/addon-options is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/airbnb/react-dates/builds/310981110?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v3.2.17</strong>

<p>2017-December-03</p>
<h4>Features</h4>
<ul>
<li>Add dotenv support for storybook in vue and react <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2345">#2345</a></li>
<li>Add addon jest <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2295">#2295</a></li>
<li>Addon-knobs: add number config options <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2371">#2371</a></li>
<li>Addon-info: Expose style for customization <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2370">#2370</a></li>
</ul>
<h4>Bug Fixes</h4>
<ul>
<li>Fix addon-actions in legacy Android browser <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2365">#2365</a></li>
<li>Remove superfluous vertical scrollbar in fullscreen <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2394">#2394</a></li>
<li>Made jest test file extension name optional <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2373">#2373</a></li>
<li>Render navigation and addons panels even when they are hidden <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2336">#2336</a></li>
<li>Fix wrong "withTests" examples + add documentation <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2398">#2398</a></li>
</ul>
<h4>Maintenance</h4>
<ul>
<li>Issue <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/2196" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="270070092" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/2196">#2196</a> - Set console.warn and console.error to throw in tests <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2297">#2297</a></li>
<li>Optimize CI workflow <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2331">#2331</a></li>
<li>Ignore shelljs in bithound <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2322">#2322</a></li>
<li>Fix netlify vue instance <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2386">#2386</a></li>
<li>Keep examples' deps up to date <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2353">#2353</a></li>
<li>Separate netlify instances <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2340">#2340</a></li>
<li>Issue 2196 fix unittest warnings <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2343">#2343</a></li>
</ul>
<h4>Documentation</h4>
<ul>
<li>Document return type of <code>date</code> knob (see <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/1489" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="244040321" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/1489">#1489</a>) <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2332">#2332</a></li>
</ul>
<h4>Dependency Upgrades</h4>
<details>
<summary>
72 PRs
</summary>
<ul>
<li>Update gatsby in /docs from 1.9.127 to 1.9.128 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2420">#2420</a></li>
<li>Update marked in /docs from 0.3.6 to 0.3.7 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2416">#2416</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.126" to "1.9.127" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.22" to "1.7.23" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.125" to "1.9.126" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.29" to "1.6.30" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.119" to "1.9.125" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.28" to "1.6.29" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-plugin-sharp</code> in <code>docs</code> from "1.6.21" to "1.6.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-autolink-headers</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-copy-linked-files</code> in <code>docs</code> from "1.5.21" to "1.5.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-images</code> in <code>docs</code> from "1.5.32" to "1.5.33" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-smartypants</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-source-filesystem</code> in <code>docs</code> from "1.5.8" to "1.5.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.21" to "1.7.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react-native</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/vue</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>danger</code> in <code>/</code> from "2.0.1" to "2.0.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint</code> in <code>/</code> from "4.11.0" to "4.12.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.8.0" to "2.9.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.3" to "3.1.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react-native</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>react-native</code> in <code>app/react-native</code> from "0.50.3" to "0.50.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/react</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/vue</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/vue</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>commander</code> in <code>/</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>lib/cli</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.2" to "3.1.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react-native</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/vue</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Update gatsby in docs from 1.9.118 to 1.9.119 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2354">#2354</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>ws</code> in <code>app/react-native</code> from "3.3.1" to "3.3.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.7.0" to "2.8.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>eslint-plugin-react</code> in <code>/</code> from "7.4.0" to "7.5.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Update gatsby in docs from 1.9.117 to 1.9.118 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2341">#2341</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.114" to "1.9.117" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Upgraded <code>gh-pages</code> in <code>docs</code> from "1.0.0" to "1.1.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Update gh-pages in / from 1.0.0 to 1.1.0 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2339">#2339</a></li>
<li>Upgraded <code>@types/react</code> in <code>addons/knobs</code> from "16.0.23" to "16.0.25" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>app/vue</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>examples/vue-kitchen-sink</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Update gatsby in docs from 1.9.112 to 1.9.114 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2333">#2333</a></li>
<li>Upgraded <code>@storybook/addon-actions</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addon-links</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addons</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/react</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Update @types/node in addons/knobs from 8.0.52 to 8.0.53 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2326">#2326</a></li>
</ul>
</details>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #879: An in-range update of @storybook/addon-links is breaking the build 🚨
## Version **3.2.17** of [@storybook/addon-links](https://github.com/storybooks/storybook) was just published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/airbnb/react-dates/compare/greenkeeper%2F%40storybook%2Faddon-links-3.2.17">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      @storybook/addon-links
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      3.2.16
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      devDependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@storybook/addon-links is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/airbnb/react-dates/builds/310980664?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v3.2.17</strong>

<p>2017-December-03</p>
<h4>Features</h4>
<ul>
<li>Add dotenv support for storybook in vue and react <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2345">#2345</a></li>
<li>Add addon jest <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2295">#2295</a></li>
<li>Addon-knobs: add number config options <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2371">#2371</a></li>
<li>Addon-info: Expose style for customization <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2370">#2370</a></li>
</ul>
<h4>Bug Fixes</h4>
<ul>
<li>Fix addon-actions in legacy Android browser <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2365">#2365</a></li>
<li>Remove superfluous vertical scrollbar in fullscreen <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2394">#2394</a></li>
<li>Made jest test file extension name optional <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2373">#2373</a></li>
<li>Render navigation and addons panels even when they are hidden <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2336">#2336</a></li>
<li>Fix wrong "withTests" examples + add documentation <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2398">#2398</a></li>
</ul>
<h4>Maintenance</h4>
<ul>
<li>Issue <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/2196" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="270070092" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/2196">#2196</a> - Set console.warn and console.error to throw in tests <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2297">#2297</a></li>
<li>Optimize CI workflow <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2331">#2331</a></li>
<li>Ignore shelljs in bithound <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2322">#2322</a></li>
<li>Fix netlify vue instance <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2386">#2386</a></li>
<li>Keep examples' deps up to date <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2353">#2353</a></li>
<li>Separate netlify instances <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2340">#2340</a></li>
<li>Issue 2196 fix unittest warnings <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2343">#2343</a></li>
</ul>
<h4>Documentation</h4>
<ul>
<li>Document return type of <code>date</code> knob (see <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/1489" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="244040321" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/1489">#1489</a>) <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2332">#2332</a></li>
</ul>
<h4>Dependency Upgrades</h4>
<details>
<summary>
72 PRs
</summary>
<ul>
<li>Update gatsby in /docs from 1.9.127 to 1.9.128 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2420">#2420</a></li>
<li>Update marked in /docs from 0.3.6 to 0.3.7 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2416">#2416</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.126" to "1.9.127" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.22" to "1.7.23" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.125" to "1.9.126" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.29" to "1.6.30" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.119" to "1.9.125" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.28" to "1.6.29" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-plugin-sharp</code> in <code>docs</code> from "1.6.21" to "1.6.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-autolink-headers</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-copy-linked-files</code> in <code>docs</code> from "1.5.21" to "1.5.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-images</code> in <code>docs</code> from "1.5.32" to "1.5.33" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-smartypants</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-source-filesystem</code> in <code>docs</code> from "1.5.8" to "1.5.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.21" to "1.7.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react-native</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/vue</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>danger</code> in <code>/</code> from "2.0.1" to "2.0.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint</code> in <code>/</code> from "4.11.0" to "4.12.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.8.0" to "2.9.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.3" to "3.1.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react-native</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>react-native</code> in <code>app/react-native</code> from "0.50.3" to "0.50.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/react</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/vue</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/vue</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>commander</code> in <code>/</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>lib/cli</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.2" to "3.1.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react-native</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/vue</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Update gatsby in docs from 1.9.118 to 1.9.119 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2354">#2354</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>ws</code> in <code>app/react-native</code> from "3.3.1" to "3.3.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.7.0" to "2.8.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>eslint-plugin-react</code> in <code>/</code> from "7.4.0" to "7.5.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Update gatsby in docs from 1.9.117 to 1.9.118 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2341">#2341</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.114" to "1.9.117" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Upgraded <code>gh-pages</code> in <code>docs</code> from "1.0.0" to "1.1.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Update gh-pages in / from 1.0.0 to 1.1.0 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2339">#2339</a></li>
<li>Upgraded <code>@types/react</code> in <code>addons/knobs</code> from "16.0.23" to "16.0.25" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>app/vue</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>examples/vue-kitchen-sink</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Update gatsby in docs from 1.9.112 to 1.9.114 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2333">#2333</a></li>
<li>Upgraded <code>@storybook/addon-actions</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addon-links</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addons</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/react</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Update @types/node in addons/knobs from 8.0.52 to 8.0.53 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2326">#2326</a></li>
</ul>
</details>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #880: An in-range update of @storybook/react is breaking the build 🚨
## Version **3.2.17** of [@storybook/react](https://github.com/storybooks/storybook) was just published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/airbnb/react-dates/compare/greenkeeper%2F%40storybook%2Freact-3.2.17">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      @storybook/react
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      3.2.16
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      devDependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@storybook/react is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/airbnb/react-dates/builds/310981511?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v3.2.17</strong>

<p>2017-December-03</p>
<h4>Features</h4>
<ul>
<li>Add dotenv support for storybook in vue and react <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2345">#2345</a></li>
<li>Add addon jest <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2295">#2295</a></li>
<li>Addon-knobs: add number config options <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2371">#2371</a></li>
<li>Addon-info: Expose style for customization <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2370">#2370</a></li>
</ul>
<h4>Bug Fixes</h4>
<ul>
<li>Fix addon-actions in legacy Android browser <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2365">#2365</a></li>
<li>Remove superfluous vertical scrollbar in fullscreen <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2394">#2394</a></li>
<li>Made jest test file extension name optional <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2373">#2373</a></li>
<li>Render navigation and addons panels even when they are hidden <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2336">#2336</a></li>
<li>Fix wrong "withTests" examples + add documentation <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2398">#2398</a></li>
</ul>
<h4>Maintenance</h4>
<ul>
<li>Issue <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/2196" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="270070092" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/2196">#2196</a> - Set console.warn and console.error to throw in tests <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2297">#2297</a></li>
<li>Optimize CI workflow <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2331">#2331</a></li>
<li>Ignore shelljs in bithound <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2322">#2322</a></li>
<li>Fix netlify vue instance <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2386">#2386</a></li>
<li>Keep examples' deps up to date <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2353">#2353</a></li>
<li>Separate netlify instances <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2340">#2340</a></li>
<li>Issue 2196 fix unittest warnings <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2343">#2343</a></li>
</ul>
<h4>Documentation</h4>
<ul>
<li>Document return type of <code>date</code> knob (see <a href="https://urls.greenkeeper.io/storybooks/storybook/issues/1489" class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="244040321" data-permission-text="Issue title is private" data-url="https://github.com/storybooks/storybook/issues/1489">#1489</a>) <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2332">#2332</a></li>
</ul>
<h4>Dependency Upgrades</h4>
<details>
<summary>
72 PRs
</summary>
<ul>
<li>Update gatsby in /docs from 1.9.127 to 1.9.128 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2420">#2420</a></li>
<li>Update marked in /docs from 0.3.6 to 0.3.7 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2416">#2416</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.126" to "1.9.127" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.22" to "1.7.23" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2406">#2406</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.125" to "1.9.126" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.29" to "1.6.30" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2399">#2399</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.119" to "1.9.125" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-link</code> in <code>docs</code> from "1.6.28" to "1.6.29" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-plugin-sharp</code> in <code>docs</code> from "1.6.21" to "1.6.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-autolink-headers</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-copy-linked-files</code> in <code>docs</code> from "1.5.21" to "1.5.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-images</code> in <code>docs</code> from "1.5.32" to "1.5.33" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-remark-smartypants</code> in <code>docs</code> from "1.4.8" to "1.4.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-source-filesystem</code> in <code>docs</code> from "1.5.8" to "1.5.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>gatsby-transformer-remark</code> in <code>docs</code> from "1.7.21" to "1.7.22" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2392">#2392</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react-native</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/react</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.1" to "1.12.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>webpack-hot-middleware</code> in <code>app/vue</code> from "2.20.0" to "2.21.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2385">#2385</a></li>
<li>Upgraded <code>danger</code> in <code>/</code> from "2.0.1" to "2.0.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint</code> in <code>/</code> from "4.11.0" to "4.12.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.8.0" to "2.9.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2380">#2380</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.3" to "3.1.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react-native</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>react-native</code> in <code>app/react-native</code> from "0.50.3" to "0.50.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/react</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/react</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>common-tags</code> in <code>app/vue</code> from "1.4.0" to "1.5.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>postcss-loader</code> in <code>app/vue</code> from "2.0.8" to "2.0.9" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2364">#2364</a></li>
<li>Upgraded <code>commander</code> in <code>/</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>lib/cli</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>react-modal</code> in <code>lib/ui</code> from "3.1.2" to "3.1.3" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react-native</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react-native</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/react</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/react</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>commander</code> in <code>app/vue</code> from "2.11.0" to "2.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Upgraded <code>webpack-dev-middleware</code> in <code>app/vue</code> from "1.12.0" to "1.12.1" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2359">#2359</a></li>
<li>Update gatsby in docs from 1.9.118 to 1.9.119 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2354">#2354</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>ws</code> in <code>app/react-native</code> from "3.3.1" to "3.3.2" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.6" to "2.5.8" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2344">#2344</a></li>
<li>Upgraded <code>eslint-config-prettier</code> in <code>/</code> from "2.7.0" to "2.8.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>eslint-plugin-react</code> in <code>/</code> from "7.4.0" to "7.5.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.5" to "2.5.6" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2342">#2342</a></li>
<li>Update gatsby in docs from 1.9.117 to 1.9.118 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2341">#2341</a></li>
<li>Upgraded <code>gatsby</code> in <code>docs</code> from "1.9.114" to "1.9.117" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Upgraded <code>gh-pages</code> in <code>docs</code> from "1.0.0" to "1.1.0" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2338">#2338</a></li>
<li>Update gh-pages in / from 1.0.0 to 1.1.0 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2339">#2339</a></li>
<li>Upgraded <code>@types/react</code> in <code>addons/knobs</code> from "16.0.23" to "16.0.25" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>addons/knobs</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>app/vue</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>app/vue</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-hot-reload-api</code> in <code>examples/vue-kitchen-sink</code> from "2.2.3" to "2.2.4" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Upgraded <code>vue-template-compiler</code> in <code>examples/vue-kitchen-sink</code> from "2.5.3" to "2.5.5" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2334">#2334</a></li>
<li>Update gatsby in docs from 1.9.112 to 1.9.114 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2333">#2333</a></li>
<li>Upgraded <code>@storybook/addon-actions</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addon-links</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/addons</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Upgraded <code>@storybook/react</code> in <code>docs</code> from "3.2.15" to "3.2.16" <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2327">#2327</a></li>
<li>Update @types/node in addons/knobs from 8.0.52 to 8.0.53 <a href="https://urls.greenkeeper.io/storybooks/storybook/pull/2326">#2326</a></li>
</ul>
</details>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by ljharb**
If there's a more robust way to do these comparisons, I'm happy to switch to that.

Closes #876. Closes #877. Closes #878. Closes #879. Closes #880.

### CODE REVIEW

File: test/components/DayPickerRangeController_spec.jsx [hunk 1]
```diff
@@ -1934,7 +1934,7 @@ describe('DayPickerRangeController', () => {
         currentMonth: today,
       });
       wrapper.instance().onNextMonthClick();
-      expect(wrapper.state().currentMonth.month()).to.equal(today.month() + 1);
+      expect(wrapper.state().currentMonth.month()).to.equal((today.month() + 1) % 12);
```
Comment (majapw) [inline test/components/DayPickerRangeController_spec.jsx]: I think this is a fine patch, but probably the more robust way would be to change this to `today.clone().add(1, 'month').month()`. What do you think?

Comment (ljharb) [reply test/components/DayPickerRangeController_spec.jsx]: Much better, will fix.
