### PR TITLE
Fix date selection issue with withPortal or appendToBody. Fixes #1535.

### LINKED ISSUE #1535: appendToBody property breaks date selection in SingleDatePicker
**react-dates version**

- react-dates@19.0.0
- react-dates@18.5.x
- react-dates@18.4.1

**Describe the bug**

When `appendToBody` is set in a `SingleDatePicker`, the picker displays correctly on click but `onDateChange` callback is never called and the picker gets closed immediately. The date doesn't update.

This actually looks like a regression from #1522 . It appears that it was introduced in 18.4.1 (18.4.0 and previous versions work as expected).

**Source code (including props configuration)**

```jsx
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      focused: props.autoFocus,
      date: props.initialDate,
    };

    this.onDateChange = this.onDateChange.bind(this);
    this.onFocusChange = this.onFocusChange.bind(this);
  }

  onDateChange(date) {
    this.setState({ date });
  }

  onFocusChange({ focused }) {
    this.setState({ focused });
  }

  render() {
   const { focused, date } = this.state; 
    return (
        <SingleDatePicker
          id="mydatepicker"
          date={date}
          focused={focused}
          onDateChange={this.onDateChange}
          onFocusChange={this.onFocusChange}
          appendToBody
        />
    );
  }
}
```

**Screenshots/Gifs**

None.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Chromium, Firefox
 - Version: 72, 65

**Is the issue reproducible in Storybook?**

I don't know how to use storybook.

**Additional context**

Let me know if I can do anything to help.

### PR DESCRIPTION
**Pull request by danedavid**
Fixes #1535 .

### CODE REVIEW

**Comment by ljharb** [comment]
This appears to be failing tests.

**Comment by danedavid** [comment]
@ljharb Ok, let me check and get back to you

**Comment by danedavid** [comment]
@ljharb Updated the PR.

File: src/components/SingleDatePicker.jsx [hunk 1]
```diff
@@ -248,7 +248,12 @@ class SingleDatePicker extends React.PureComponent {
 
   onFocusOut(e) {
     const { onFocusChange } = this.props;
-    if (this.container.contains(e.relatedTarget || e.target)) return;
+    if (
+      this.dayPickerContainer
+      && this.dayPickerContainer.contains(e.relatedTarget || e.target)
```
Comment (ljharb) [inline src/components/SingleDatePicker.jsx]: I’m not sure this is the right change - is it possible the relevant tests were mocking this.container but need to be updated to mock this.dayPickerContainer?

Comment (danedavid) [reply src/components/SingleDatePicker.jsx]: Even I thought of that. The fact is that there are always 2 refs - the outer ref `this.container`, and the inner ref `this.dayPickerContainer`. The issue was caused because the wrong container ref was being searched in case of elements rendered in portal. So I referred to `DateRangePicker.jsx`, where I saw that `this.dayPickerContainer` was the one being used in `focusOut` handler. And thus the change.
So should we update the tests, or is the change wrong?

Comment (ljharb) [reply src/components/SingleDatePicker.jsx]: Your change might be perfect :-) but maybe you could add tests that would help ensure it's not broken in the future?

Comment (danedavid) [reply src/components/SingleDatePicker.jsx]: I've changed the ref being used inside the test, and reverted the previous check. @ljharb

**Comment by monokrome** [comment]
@majapw Not sure that my fix didn't work. Seems unrelated to me - which use case wasn't working in 19.0.2?

**Comment by majapw** [comment]
@monokrome Sorry I wasn't clear! This issue seemed very similar to https://github.com/airbnb/react-dates/issues/1522 (clicking anywhere closes the SingleDatePicker) as it was related to the SDP autoclosing and the `appendToBody` prop. This seemed like a specific edgecase of that (the description of the use case is in the linked issue) and both were rooted in the v18.4.1 changes. Thanks for taking a look!
