### PR TITLE
[Fix] `DateRangePickerInputController`: fix onClose method

### LINKED ISSUE #1892: onClose returns incorrect endDate if it's been entered manually in the input
If dates are not choosed from calendar but entered manually in inputs onClose handler returns null or previous date in endDate. It is visible in storybook https://airbnb.io/react-dates/?path=/story/drp-calendar-props--with-onclose-handler

### PR DESCRIPTION
**Pull request by mmarkelov**
Fixes #1892 
I suppose following issue because of firing **onClearFocus** with start and end dates from props, that's not right it should use values inside **onEndDateChange** function

### CODE REVIEW

File: test/components/DateRangePickerInputController_spec.jsx [hunk 1]
```diff
@@ -222,6 +222,23 @@ describe('DateRangePickerInputController', () => {
...
+        it('calls props.onClose with props.startDate and provided end date', () => {
+          const onCloseStub = sinon.stub();
+          const wrapper = shallow((
+            <DateRangePickerInputController
+              onClose={onCloseStub}
+              startDate={startDate}
+            />
+          ));
+          wrapper.instance().onEndDateChange(validFutureDateString);
+          expect(onCloseStub.callCount).to.equal(1);
```
Comment (ljharb) [inline test/components/DateRangePickerInputController_spec.jsx]:
```suggestion
          expect(onCloseStub).to.have.property('callCount', 1);
```

File: test/components/DateRangePickerInputController_spec.jsx [hunk 2]
```diff
@@ -222,6 +222,23 @@ describe('DateRangePickerInputController', () => {
...
+
+          const onCloseArgs = onCloseStub.getCall(0).args[0];
```
Comment (ljharb) [inline test/components/DateRangePickerInputController_spec.jsx]:
```suggestion
          const [onCloseArgs] = onCloseStub.getCall(0).args;
```

File: test/components/DateRangePickerInputController_spec.jsx [hunk 3]
```diff
@@ -222,6 +222,23 @@ describe('DateRangePickerInputController', () => {
...
+          const futureDate = moment(validFutureDateString);
+          expect(onCloseArgs.startDate).to.equal(startDate);
```
Comment (ljharb) [inline test/components/DateRangePickerInputController_spec.jsx]:
```suggestion
          expect(onCloseArgs).to.have.property('startDate', startDate);
```

**Comment by tjhart** [comment]
If I understand correctly, these changes will fix #1892 ? It's causing issues for me as well. What's left to get a release out that includes this?

**Comment by tjhart** [comment]
@ljharb Leaving another ping about this. I see that the changes have been approved, and I haven't found that another issue superseding this one. Can I do anything to help get this into a release?
