### PR TITLE
[Fix] isTouchDevice: improve detection logic

### LINKED ISSUE #515: Hover on a day on Firefox doesn't add classes to the day
When I hover on the calendar on firefox nothing happens. After debugging a little bit, I think there is a bug in the `isTouchDevice` function. 

`ontouchstart` is defined in firefox, but it has a `null` value.

screen shot 2017-05-16 at 5 35 09 pm

Since the `onDayMouseEnter` and `onDayMouseLeave` will return if `this.isTouchDevice`, the hover logic doesn't get applied on Firefox.

### PR DESCRIPTION
**Pull request by tagoro9**
`window.ontouchstart` is a defiend property in Firefox with a value of null. This PR fixes the `isTouchDevice` function to check that `ontouchstart != null`.

This PR fixes #515.

### CODE REVIEW

File: src/utils/isTouchDevice.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
 export default function isTouchDevice() {
-  return !!(typeof window !== 'undefined' && 'ontouchstart' in window) ||
+  return !!(typeof window !== 'undefined' && window.ontouchstart != null) ||
```
Comment (ljharb) [inline src/utils/isTouchDevice.js]: What value will `window.ontouchstart` have in a browser that supports touch?

However, https://hacks.mozilla.org/2013/04/detecting-touch-its-the-why-not-the-how/ seems to imply that we should be checking a few more things.

Comment (tagoro9) [inline src/utils/isTouchDevice.js]: By looking at what Modernizr [does](https://github.com/Modernizr/Modernizr/blob/5eea7e2a213edc9e83a47b6414d0250468d83471/feature-detects/touchevents.js), it looks like they do some more checks too. Even though it is not still a bug I could still update this to have a better check.

Comment (majapw) [inline src/utils/isTouchDevice.js]: I think that would be super helpful!

Comment (ljharb) [inline src/utils/isTouchDevice.js]: Agreed, that'd be appreciated :-)

**Comment by tagoro9** [comment]
I updated the `isTouchDevice` function to also check for mxMaxTouchPoints, which seems to be used on some old IE versions and to also use the `DocumentTouch` check, which is the one used by `Modernizr`.

They also use some media queries, but that involves adding a lot of vendor prefixes:

https://drafts.csswg.org/mediaqueries/#pointer
https://www.quirksmode.org/css/mediaqueries/touch.html

These two articles seemed relevant:

http://www.stucox.com/blog/you-cant-detect-a-touchscreen/
https://medium.com/@david.gilbertson/the-only-way-to-detect-touch-with-javascript-7791a3346685 

Let me know what you think of this approach.

File: test/utils/isTouchDevice_spec.js [hunk 2]
```diff
@@ -26,6 +27,20 @@ describeIfNoWindow('isTouchDevice', () => {
...
+    .withOverride(() => window, 'DocumentTouch', () => DocumentTouch)
+    .withGlobal('document', () => new (function Document() {})())
+    .it('returns false when document is not an instance of DocumentTouch', () => {
+      expect(isTouchDevice()).to.equal(false);
+    });
+
+    wrap()
+    .withOverride(() => window, 'DocumentTouch', () => DocumentTouch)
+    .withGlobal('document', () => new DocumentTouch())
+    .it('returns true when document is an instance of DocumentTouch', () => {
```
Comment (ljharb) [inline test/utils/isTouchDevice_spec.js]: might be nice to assert that document is an instance of DocumentTouch, as well

File: test/utils/isTouchDevice_spec.js [hunk 3]
```diff
@@ -26,6 +27,20 @@ describeIfNoWindow('isTouchDevice', () => {
     .it('returns true with `window.ontouchstart', () => {
       expect(isTouchDevice()).to.equal(true);
     });
+
+    wrap()
+    .withOverride(() => window, 'DocumentTouch', () => DocumentTouch)
+    .withGlobal('document', () => new (function Document() {})())
+    .it('returns false when document is not an instance of DocumentTouch', () => {
```
Comment (tagoro9) [inline test/utils/isTouchDevice_spec.js]: Added.

File: test/utils/isTouchDevice_spec.js (hunk 2 above)
Comment (tagoro9) [inline test/utils/isTouchDevice_spec.js]: Added.

File: src/utils/isTouchDevice.js [hunk 4]
```diff
@@ -1,4 +1,11 @@
 export default function isTouchDevice() {
-  return !!(typeof window !== 'undefined' && 'ontouchstart' in window) ||
-    !!(typeof navigator !== 'undefined' && navigator.maxTouchPoints);
+  return (
+    !!(typeof window !== 'undefined' &&
```
Comment (ljharb) [inline src/utils/isTouchDevice.js]: This logic could probably be split up into if/elses at this point, but nbd
