### PR TITLE
Fix: use constructor-bound methods for ref callbacks

### LINKED ISSUE #437: TypeError: Cannot read property 'contains' of null
What error is this? How to solve?

```
OutsideClickHandler.js:1 Uncaught TypeError: Cannot read property 'contains' of null
    at OutsideClickHandler.onOutsideClick (webpack:///./~/react-dates/lib/components/OutsideClickHandler.js?:1:3926)
    at eval (webpack:///./~/consolidated-events/lib/TargetEventHandlers.js?:1:1684)
    at Array.forEach (native)
    at TargetEventHandlers.handleEvent (webpack:///./~/consolidated-events/lib/TargetEventHandlers.js?:1:1620)
```

### PR DESCRIPTION
**Pull request by ljharb**
Use constructor-bound methods for ref callbacks instead of arrow functions.

Because this avoids creating a new function every render, it's both more performant, and also ensures React never sees two `!==` ref callbacks, which thus causes it to call the old one with `null` and the new one with the ref, which can sometimes cause issues like #437.

Separately, DayPickerKeyboardShortcuts has a ref but was an SFC, which makes no sense - so this also fixes it to be a class-based component.

Fixes #437.

### CODE REVIEW

File: src/components/DateRangePicker.jsx [hunk 1]
```diff
@@ -116,6 +116,9 @@ export default class DateRangePicker extends React.Component {
     this.showKeyboardShortcutsPanel = this.showKeyboardShortcutsPanel.bind(this);
 
     this.responsivizePickerPosition = this.responsivizePickerPosition.bind(this);
+
+    this.setDayPickerContainerRef = this.setDayPickerContainerRef.bind(this);
+    this.setDayPickerRef = this.setDayPickerRef(this);
```
Comment (calinoracation) [inline src/components/DateRangePicker.jsx]: Looks to be missing a `.bind`.

Comment (ljharb) [inline src/components/DateRangePicker.jsx]: whoops, thanks!

File: src/components/CalendarDay.jsx [hunk 2]
```diff
@@ -112,7 +122,7 @@ export default class CalendarDay extends React.Component {
       <td className={className} style={daySizeStyles}>
         <button
           type="button"
-          ref={(ref) => { this.buttonRef = ref; }}
+          ref={this.setButtonRef}
```
Comment (majapw) [inline src/components/CalendarDay.jsx]: This is a silly effect of react

Comment (ljharb) [inline src/components/CalendarDay.jsx]: agreed
