### PR TITLE
[Fix] `DateInput`: `isTouchDevice` should only be determined in `componentDidMount`

### LINKED ISSUE #335: Server Rendering Checksum Error
When server-rendering we get a checksum error because `DateInput` is using `isTouchDevice` to set the `readOnly` attribute on the input. `isTouchDevice` is always rendering `false` on the server (since `window` isn't defined) regardless of whether the client device is actually a touchDevice. What's worse, this causes checksum errors even if the device is not a touch device anyway:

```
       Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
        (client)  autocomplete="off" readonly="" aria-des
        (server)  autocomplete="off" aria-describedby=""
```

One way to fix this might be to move the device type check to run only after the component mounts and just use a constant value when on the server and on the initial render. Or, alternatively, you could allow the user to specify the value themselves if they so choose and thus figure out their own fix, such as guessing the device type on the server via the request's user agent header (similar to this discussion for media queries in react-responsive: https://github.com/contra/react-responsive/issues/43).

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #335.

### CODE REVIEW

File: src/components/DateInput.jsx [hunk 1]
```diff
@@ -89,7 +92,10 @@ export default class DateInput extends React.Component {
   }
 
   render() {
-    const { dateString } = this.state;
+    const {
+      dateString,
+      isTouchDevice: isTouch,
```
Comment (majapw) [inline src/components/DateInput.jsx]: I'm confused about the need for this name change. Can't we just keep this as `isTouchDevice`?

File: .eslintrc [hunk 2]
```diff
@@ -9,5 +9,6 @@
   "rules": {
     "no-mixed-operators": [2, { "allowSamePrecedence": true }],
     "jsx-a11y/no-static-element-interactions": 1, // TODO: enable
+    "react/no-did-mount-set-state": 0, // necessary for server-rendering
```
Comment (majapw) [inline .eslintrc]: Can we exclusively put this on the `DateInput` instead of as a universal exception?

Comment (ljharb) [inline .eslintrc]: I can, but it should be a universal exception, because it's necessary for *any* component. I need to disable this rule upstream in the airbnb config too - `setState` in `componentDidMount` is a good thing.

File: src/components/DateInput.jsx (hunk 1 above)
Comment (ljharb) [inline src/components/DateInput.jsx]: That identifier name is already used on [line 5](https://github.com/airbnb/react-dates/pull/336/files#diff-f090ce99cecab0a8a3afc65f42d45527R5)

File: .eslintrc (hunk 2 above)
Comment (majapw) [inline .eslintrc]: Really?

File: src/components/DateInput.jsx (hunk 1 above)
Comment (majapw) [inline src/components/DateInput.jsx]: I see

File: .eslintrc (hunk 2 above)
Comment (ljharb) [inline .eslintrc]: Every single one of airbnb's hypernova components works like that already. We can definitely strive to avoid it, but it's not possible to avoid for client-required functionality.

Comment (majapw) [inline .eslintrc]: I guess that's fair, but given that this repo is small, I would prefer to turn it off on a case by case basis.

Comment (ljharb) [inline .eslintrc]: If you prefer that I can do it - but we might need to make the same change in any component that has touch detection.
