### PR TITLE
Handle minimumNights when changing startDate

### LINKED ISSUE #978: minimumNights is not handled when changing startDate
**How to reproduce**

Set the default dates as `startDate = 22` and `endDate = 25` of January.

Set `minimumNights = 0`.

Change the end date to `22`, it works.

Refresh / reset the default values.

Now change the start date to `25`, it doesn't work: `endDate` equals `null`.

**How to fix it**

It happens [here](https://github.com/airbnb/react-dates/blob/2db60a8f4301fa361d2a5a51b787153bbe27fcd9/src/components/DayPickerRangeController.jsx#L450):

    if (focusedInput === START_DATE) {
      ..
      if (isInclusivelyAfterDay(day, endDate)) {
        endDate = null;
      }
    }

If you look few lines below, the block `if (focusedInput === END_DATE)` handles `minimumNights`:

    if (focusedInput === END_DATE) {
      const firstAllowedEndDate = startDate && startDate.clone().add(minimumNights, 'days');
      ...
    }

I propose to do the same for the block `if (focusedInput === START_DATE)`:

    const lastAllowedStartDate = endDate && endDate.clone().subtract(minimumNights, 'days');

### PR DESCRIPTION
**Pull request by ggregoire**
Fixes #978

### CODE REVIEW

File: src/components/DayPickerRangeController.jsx [hunk 1]
```diff
@@ -451,11 +451,13 @@ export default class DayPickerRangeController extends React.Component {
...
       }
     } else if (focusedInput === START_DATE) {
+      const lastAllowedStartDate = endDate && endDate.clone().subtract(minimumNights, 'days');
+
       onFocusChange(END_DATE);
 
       startDate = day;
 
-      if (isInclusivelyAfterDay(day, endDate)) {
+      if (!isInclusivelyAfterDay(lastAllowedStartDate, day) || isAfterDay(startDate, endDate)) {
```
Comment (majapw) [inline src/components/DayPickerRangeController.jsx]: This might be a bit cleaner if you wrote:
```
if (isBeforeDay(lastAllowedStartDate, day) || isAfterDay(startDate, endDate))
```

**Comment by sdjidjev** [comment]
i don't see any issues with this PR! i'll let @majapw do the final approval.
